global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'devsecops-local'
    environment: 'development'

rule_files:
  - "alert.rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # DevSecOps Webapp
  - job_name: 'webapp'
    static_configs:
      - targets: ['devsecops-webapp:3000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    scrape_timeout: 10s
    honor_labels: false
    params:
      format: ['prometheus']

  # Alternative webapp target (if container name differs)
  - job_name: 'webapp-alt'
    static_configs:
      - targets: ['webapp:3000', '127.0.0.1:3000', 'localhost:3000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Alternative cAdvisor target
  - job_name: 'cadvisor-alt'
    static_configs:
      - targets: ['cadvisor:8081']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Docker daemon metrics (if enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 15s
    metrics_path: '/metrics'